server:
  port: 8301
spring:
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: admin
        password: 1234
  application:
    name: CMICT-Gateway
  cloud:
    gateway:
      routes:
        - id: CMICT-Auth
          uri: lb://CMICT-Auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/CMICT-Auth
        - id: CMICT-Server-System
          uri: lb://CMICT-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/CMICT-Server-System
        - id: CMICT-Server-activiti
          uri: lb://CMICT-Server-Activiti
          predicates:
            - Path=/activiti/**
          filters:
            - name: Hystrix
              args:
                name: activitifallback
                fallbackUri: forward:/fallback/CMICT-Server-Activiti
      default-filters:
        - StripPrefix=1

mybatis-plus:
  type-aliases-package: com.cmict.entity.system
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS