server:
  port: 8101


spring:
  application:
    name: CMICT-Auth

mybatis-plus:
  type-aliases-package: com.cmict.entity.system
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

## ADMIN客户端信息
info:
  app:
    name: ${spring.application.name}
    description: "认证服务器"
    version: "1.0-SNAPSHOT"
management:
  endpoints:
    web:
      exposure:
        ##全部端点暴露给admin Server
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
