server:
  port: 8201

spring:
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: admin
        password: 1234
  application:
    name: CMICT-Server-System

mybatis-plus:
    type-aliases-package: com.cmict.entity.system
    mapper-locations: classpath:mapper/*/*.xml
    configuration:
      jdbc-type-for-null: null
    global-config:
      banner: false

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: BASIC
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

logging:
  level:
    com.cmict.server.system.feign.HornClient: DEBUG

info:
  app:
    name: ${spring.application.name}
    description: "系统"
    version: "1.0-SNAPSHOT"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS